apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: utxorpcports.demeter.run
spec:
  group: demeter.run
  names:
    categories:
    - demeter-port
    kind: UtxoRpcPort
    plural: utxorpcports
    shortNames:
    - utxoport
    singular: utxorpcport
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.operatorVersion
      name: Operator Version
      type: string
    - jsonPath: .spec.network
      name: Network
      type: string
    - jsonPath: .spec.throughputTier
      name: Throughput Tier
      type: string
    - jsonPath: .spec.utxorpcVersion
      name: UtxoRPC Version
      type: string
    - jsonPath: .status.endpointUrl
      name: Endpoint URL
      type: string
    - jsonPath: .status.authenticatedEndpointUrl
      name: Authenticated Endpoint URL
      type: string
    - jsonPath: .status.authToken
      name: Auth Token
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for UtxoRpcPortSpec via `CustomResource`
        properties:
          spec:
            properties:
              network:
                type: string
              operatorVersion:
                type: string
              throughputTier:
                type: string
              utxorpcVersion:
                type: string
            required:
            - network
            - operatorVersion
            - throughputTier
            - utxorpcVersion
            type: object
          status:
            nullable: true
            properties:
              authToken:
                type: string
              authenticatedEndpointUrl:
                nullable: true
                type: string
              endpointUrl:
                type: string
            required:
            - authToken
            - endpointUrl
            type: object
        required:
        - spec
        title: UtxoRpcPort
        type: object
    served: true
    storage: true
    subresources:
      status: {}
